name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-x64-msvc
            runner: windows-2025
            target: X86
            generator: "Visual Studio 17 2022"
            cmake_flags: "-A x64"

          - name: windows-arm64-msvc
            runner: windows-11-arm
            target: AArch64
            generator: "Visual Studio 17 2022"
            cmake_flags: "-A ARM64"

          - name: windows-x64-mingw
            runner: windows-2025
            target: X86
            generator: Ninja
            cmake_flags: ""

          - name: windows-arm64-mingw
            runner: windows-11-arm
            target: AArch64
            generator: Ninja
            cmake_flags: ""

          - name: macos-x64
            runner: macos-13
            target: X86
            generator: Ninja
            cmake_flags: ""

          - name: macos-arm64
            runner: macos-15
            target: AArch64
            generator: Ninja
            cmake_flags: ""

          - name: linux-x64
            runner: ubuntu-24.04
            target: X86
            generator: Ninja
            cmake_flags: ""

          - name: linux-arm64
            runner: ubuntu-24.04-arm
            target: AArch64
            generator: Ninja
            cmake_flags: ""

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    env:
      GH_TOKEN: ${{ github.token }}
      VERSION: ${{ github.event.inputs.version }}
      SOURCE: llvm-project-${{ github.event.inputs.version }}.src

    steps:
      - name: Download Source
        shell: bash
        run: gh release download "llvmorg-$VERSION" -R "llvm/llvm-project" -p "$SOURCE.tar.xz"

      - name: Extract Source
        shell: bash
        run: tar xf "$SOURCE.tar.xz" || true

      - name: Build
        shell: bash
        run: |
          cd "$SOURCE"
          cmake -S llvm -B build -G "${{ matrix.generator }}" ${{ matrix.cmake_flags }} \
            -DCMAKE_BUILD_TYPE=MinSizeRel \
            -DCMAKE_INSTALL_PREFIX=install \
            -DLLVM_TARGETS_TO_BUILD=${{ matrix.target }} \
            -DLLVM_ENABLE_PROJECTS="clang"
          cmake --build build -t install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ env.VERSION }}-${{ matrix.name }}
          path: ${{ env.SOURCE }}/install
          compression-level: 9

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Release Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          files: artifacts/**/*
