name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-x64
            runner: windows-2025
            target: X86
            unix: false
          - name: windows-arm64
            runner: windows-11-arm
            target: AArch64
            unix: false
          - name: macos-x64
            runner: macos-13
            target: X86
            unix: true
          - name: macos-arm64
            runner: macos-15
            target: AArch64
            unix: true
          - name: linux-x64
            runner: ubuntu-24.04
            target: X86
            unix: true
          - name: linux-arm64
            runner: ubuntu-24.04-arm
            target: AArch64
            unix: true

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    env:
      GH_TOKEN: ${{ github.token }}
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Download Source
        shell: bash
        run: gh release download "llvmorg-$VERSION" -R "llvm/llvm-project" -p "llvm-project-$VERSION.src.tar.xz"

      - name: Extract Source (UNIX)
        if: ${{ matrix.unix }}
        shell: bash
        run: tar xf "llvm-project-$VERSION.src.tar.xz"

      - name: Extract Source (Windows)
        if: ${{ !matrix.unix }}
        shell: bash
        run: |
          7z x "llvm-project-$VERSION.src.tar.xz"
          7z x "llvm-project-$VERSION.src.tar"

      - name: Build
        shell: bash
        run: |
          cd "llvm-project-$VERSION.src"
          cmake -S llvm -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=MinSizeRel \
            -DCMAKE_INSTALL_PREFIX=install \
            -DLLVM_TARGETS_TO_BUILD=${{ matrix.target }}
          mkdir install
          touch install/temp

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ env.VERSION }}-${{ matrix.name }}
          path: install
          compression-level: 9
